(() => {
  "use strict";
  const EXTRA_ID = "slides-41-50-injected";
  const logo = '<img class="aepd-logo" src="assets/aepd-logo.svg" alt="AEPD – Agencia Española de Protección de Datos" />';
  const top = (txt) => `<header class="topbar"><div class="brand">${logo}</div><p>${txt}</p></header>`;
  const chips = (items, cls="aepd-chip-grid-41") => `<div class="${cls}">${items.map(([a,b]) => `<article><span>${a}</span><strong>${b}</strong></article>`).join("")}</div>`;
  const copy = (k,h,b,items,cls) => `<div class="copy-column"><p class="kicker">${k}</p><h2>${h}</h2><p class="body-copy">${b}</p>${items ? chips(items,cls) : ""}</div>`;
  const section = ({title,bg,eyebrow,layout,left,right,notes}) => `<section class="slide-page" data-title="${title}" data-background-color="${bg}"><div class="slide-inner">${top(eyebrow)}<main class="${layout}">${left}${right}</main></div><aside class="notes">${notes}</aside></section>`;
  const panel = (svg, cls="") => `<figure class="diagram-panel-41 ${cls}">${svg}</figure>`;
  const line = (t) => `<text x="56" y="68" font-size="15" font-weight="850" fill="#c74756" data-fit-width="620" data-min-font-size="11.5">${t}</text>`;
  const box = (x,y,w,h,fill,t1,t2="") => { const dark=fill==="#17385f"||fill==="#254f7d"; return `<g transform="translate(${x} ${y})"><rect width="${w}" height="${h}" rx="22" fill="${fill}"/><text x="${w/2}" y="${Math.round(h*.42)}" text-anchor="middle" font-size="16" font-weight="850" fill="${dark?'#fff':'#17385f'}" data-fit-width="${w-28}" data-min-font-size="11.5">${t1}</text>${t2?`<text x="${w/2}" y="${Math.round(h*.69)}" text-anchor="middle" font-size="12.5" fill="${dark?'#dbe6f2':'#66778a'}" data-fit-width="${w-28}" data-min-font-size="10.5">${t2}</text>`:""}</g>`; };
  const svg = (label, inner, h=470) => `<svg class="safe-diagram" viewBox="0 0 760 ${h}" role="img" aria-label="${label}"><rect width="760" height="${h}" rx="34" fill="#fff"/><rect x="28" y="28" width="704" height="${h-56}" rx="28" fill="#fbf8f2" stroke="#e8dfd1"/><g font-family="Inter,Arial">${inner}</g></svg>`;

  function injectSlides41To50(){
    const root = document.querySelector(".reveal .slides");
    if(!root || document.getElementById(EXTRA_ID)) return;
    const style=document.createElement("style");
    style.id=EXTRA_ID;
    style.textContent=`
      .aepd41-layout,.aepd42-layout,.aepd43-layout,.aepd44-layout,.aepd46-layout,.aepd47-layout,.aepd48-layout,.aepd49-layout{display:grid;gap:52px;align-items:center;flex:1;min-height:0;}
      .aepd41-layout,.aepd43-layout,.aepd46-layout,.aepd48-layout,.aepd49-layout{grid-template-columns:minmax(0,1fr) 640px;}.aepd42-layout,.aepd44-layout,.aepd47-layout{grid-template-columns:640px minmax(0,1fr);}      
      .diagram-panel-41{margin:0;height:430px;overflow:hidden;border:0;border-radius:30px;background:transparent;box-shadow:none}.diagram-panel-41.tall{height:470px}.diagram-panel-41 svg{display:block;width:100%;height:100%;overflow:hidden}
      .aepd41-layout h2,.aepd42-layout h2,.aepd43-layout h2,.aepd44-layout h2,.aepd46-layout h2,.aepd47-layout h2,.aepd48-layout h2,.aepd49-layout h2{font-size:49px;line-height:1.01}.aepd41-layout .body-copy,.aepd42-layout .body-copy,.aepd43-layout .body-copy,.aepd44-layout .body-copy,.aepd46-layout .body-copy,.aepd47-layout .body-copy,.aepd48-layout .body-copy,.aepd49-layout .body-copy{font-size:20px!important;line-height:1.24!important}
      .aepd-chip-grid-41{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:24px}.aepd-chip-grid-41.two{grid-template-columns:repeat(2,minmax(0,1fr))}.aepd-chip-grid-41 article{min-height:80px;padding:13px 14px;overflow:hidden;border-top:2px solid rgba(199,71,86,.34);border-radius:0 0 20px 20px;background:rgba(255,255,255,.58)}.aepd-chip-grid-41 span{color:var(--gold);font-size:10px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.aepd-chip-grid-41 strong{display:block;margin-top:7px;color:var(--blue-deep);font-size:17px;line-height:1.08;overflow-wrap:anywhere}
      .aepd45-layout{display:flex;flex-direction:column;gap:22px;flex:1;min-height:0}.aepd45-layout .copy-column{max-width:1260px}.aepd45-layout h2{font-size:51px;line-height:1.01}.authority-control-map{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.authority-control-map article{min-height:238px;padding:24px;border-radius:28px;background:rgba(255,255,255,.78);border:1px solid rgba(31,61,99,.10);box-shadow:0 18px 48px rgba(31,61,99,.08)}.authority-control-map span{color:var(--red);font-size:12px;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.authority-control-map strong{display:block;margin-top:12px;color:var(--blue-deep);font-size:28px;line-height:1.02}.authority-control-map p{margin:12px 0 0!important;color:var(--muted);font-size:16px!important;line-height:1.2!important}.authority-control-list{display:grid;gap:10px;margin-top:16px}.authority-control-list b{padding:9px 11px;border-radius:14px;background:rgba(31,61,99,.06);color:var(--blue-deep);font-size:13px;line-height:1.1}
      .edpb50-transition{display:grid;grid-template-columns:minmax(0,1fr) 560px;gap:72px;align-items:center;flex:1}.edpb50-transition h2{font-size:72px;line-height:.93;letter-spacing:-.06em}.edpb50-card{height:470px;padding:36px;border-radius:40px;background:linear-gradient(145deg,#17385f,#254f7d);box-shadow:0 30px 80px rgba(31,61,99,.22);display:flex;flex-direction:column;justify-content:center}.edpb50-card span{color:#f1b434;font-size:13px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.edpb50-card strong{display:block;margin-top:16px;color:#fff;font-size:42px;line-height:.98;letter-spacing:-.045em}.edpb50-card p{margin:18px 0 0!important;color:#dbe6f2;font-size:16px!important;line-height:1.25!important}.edpb50-card .mini{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:28px}.edpb50-card .mini b{padding:11px 8px;border-radius:15px;background:rgba(255,255,255,.09);color:#fff;text-align:center;font-size:12px;line-height:1.08}
    `;
    document.head.appendChild(style);

    const s41 = section({title:"Origen y fundamento jurídico de la AEPD",bg:"#fffdf9",eyebrow:"AEPD · origen constitucional e histórico",layout:"aepd41-layout",left:copy("Una autoridad anterior al RGPD","La AEPD nace de una trayectoria constitucional y europea que ya exigía control independiente antes del RGPD.","Su fundamento se conecta con el artículo 18.4 CE, la doctrina constitucional, el Convenio 108, la Carta de Derechos Fundamentales y la creación de la Agencia en 1992.",[["1978","art. 18.4 CE"],["1992/94","creación y funcionamiento"],["UE/CoE","Convenio 108 y Carta"]]),right:panel(svg("Origen jurídico de la AEPD",line("AEPD · FUNDAMENTO JURÍDICO")+`${box(74,112,170,86,"#eef3f8","Constitución","art. 18.4")}${box(294,112,170,86,"#f7f1e7","TC","STC 292/2000")}${box(516,112,170,86,"#eef3f8","Convenio 108","1981")}${box(184,264,170,86,"#fff0f1","Carta UE","art. 8")}${box(406,264,170,86,"#17385f","AEPD","1992 / 1994")}<g stroke="#c74756" stroke-width="3" fill="none" stroke-linecap="round"><path d="M244 155h46"/><path d="M464 155h46"/><path d="M380 205v52"/></g><rect x="118" y="390" width="524" height="34" rx="17" fill="#fff" stroke="#e4ddd2"/><text x="380" y="413" text-anchor="middle" font-size="13.5" font-weight="850" fill="#17385f" data-fit-width="480">La Agencia es anterior al RGPD y consolida una garantía constitucional.</text>`)),notes:"Relacionar el artículo 18.4 CE con la doctrina constitucional sobre el derecho fundamental a la protección de datos, el Convenio 108 y la Carta de Derechos Fundamentales. Recordar que la AEPD fue creada en 1992 y comenzó a funcionar en 1994: es anterior al RGPD."});

    const s42 = section({title:"Organigrama de la AEPD",bg:"#faf7f1",eyebrow:"AEPD · estructura práctica",layout:"aepd42-layout",left:panel(svg("Organigrama funcional de la AEPD",line("ORGANIGRAMA FUNCIONAL AEPD")+`<g transform="translate(270 100)"><rect width="220" height="78" rx="24" fill="#17385f"/><text x="110" y="34" text-anchor="middle" font-size="24" font-weight="900" fill="#fff">AEPD</text><text x="110" y="57" text-anchor="middle" font-size="12" fill="#dbe6f2">autoridad independiente</text></g><g stroke="#c74756" stroke-width="2.4" fill="none" opacity=".62"><path d="M380 178v42M380 220H128M380 220H632"/><path d="M128 220v28M296 220v28M464 220v28M632 220v28"/><path d="M210 350v25M380 350v25M550 350v25"/></g>${box(54,248,148,84,"#eef3f8","Presidencia","dirección")}${box(222,248,148,84,"#f7f1e7","Adjuntía","apoyo")}${box(390,248,148,84,"#fff0f1","Consejo","consultivo")}${box(558,248,148,84,"#eef3f8","Inspección","supervisión")}${box(126,375,168,72,"#f7f1e7","Promoción","autorizaciones")}${box(296,375,168,72,"#eef3f8","Secretaría","general")}${box(466,375,168,72,"#fff0f1","Servicio","jurídico")}` ,520),"tall"),right:copy("Cómo se reparte el trabajo","El organigrama permite visualizar la división entre dirección, supervisión, promoción, autorizaciones, gestión y asesoramiento jurídico.","No se trata de memorizar cajas, sino de entender qué unidades hacen posible las funciones explicadas en el RGPD y la LOPDGDD.",[["Dirección","Presidencia y Adjuntía"],["Actividad","inspección, promoción y autorizaciones"],["Soporte","secretaría y servicio jurídico"]]),notes:"Explicar de forma práctica cómo se organiza la Agencia: Presidencia, Adjuntía, Consejo Consultivo, áreas de inspección, promoción y autorizaciones, Secretaría General y Servicio Jurídico. La finalidad no es memorizar nombres, sino visualizar cómo se reparten las funciones."});

    const s43 = section({title:"La AEPD como autoridad independiente",bg:"#fffdf9",eyebrow:"Independencia funcional · controles jurídicos",layout:"aepd43-layout",left:copy("Independiente no significa aislada","La AEPD actúa con independencia funcional, presupuesto propio y autonomía, pero integrada en el sector público y sometida al Derecho.","La independencia protege el ejercicio imparcial de sus funciones; los controles aseguran legalidad, responsabilidad y tutela judicial.",[["Independencia","sin instrucciones en sus funciones"],["Sector público","régimen jurídico y presupuestario"],["Control","tribunales y reglas jurídicas"]]),right:panel(svg("La independencia de la AEPD y sus controles",line("AEPD · INDEPENDENCIA CON CONTROLES")+`<g transform="translate(250 110)"><circle cx="130" cy="120" r="108" fill="#17385f"/><text x="130" y="110" text-anchor="middle" font-size="18" font-weight="850" fill="#f1b434">AUTONOMÍA</text><text x="130" y="142" text-anchor="middle" font-size="23" font-weight="900" fill="#fff" data-fit-width="170">funcional</text></g>${box(60,130,160,82,"#eef3f8","Presupuesto","propio")}${box(540,130,160,82,"#f7f1e7","Sector público","Ley 40/2015")}${box(60,300,160,82,"#fff0f1","No instrucciones","imparcialidad")}${box(540,300,160,82,"#eef3f8","Control judicial","legalidad")}<g stroke="#c74756" stroke-width="2.5" fill="none" opacity=".7"><path d="M220 171L270 190"/><path d="M540 171L490 190"/><path d="M220 341L276 276"/><path d="M540 341L484 276"/></g>`)),notes:"Explicar que la AEPD tiene presupuesto propio y autonomía funcional y debe ejercer sus funciones con independencia. Conectar con el Título VI del RGPD, la Ley 40/2015 y la LOPDGDD. Independencia no significa ausencia de controles: la Agencia forma parte del sector público y está sometida a las reglas jurídicas correspondientes."});

    const s44 = section({title:"Poderes de la AEPD",bg:"#faf7f1",eyebrow:"RGPD art. 58 · traducción española",layout:"aepd44-layout",left:panel(svg("Poderes de la AEPD como traducción institucional del artículo 58 RGPD",line("AEPD · PODERES EN ESPAÑA")+`<g transform="translate(250 96)"><rect width="260" height="68" rx="24" fill="#17385f"/><text x="130" y="30" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">ARTÍCULO 58 RGPD</text><text x="130" y="54" text-anchor="middle" font-size="24" font-weight="900" fill="#fff">Poderes de la AEPD</text></g><g stroke="#c74756" stroke-width="2.8" fill="none" stroke-linecap="round" stroke-linejoin="round" opacity=".68"><path d="M380 164v30"/><path d="M135 194H625"/><path d="M135 194v26"/><path d="M380 194v26"/><path d="M625 194v26"/><path d="M380 310v18"/><path d="M250 328H510"/><path d="M250 328v28"/><path d="M510 328v28"/></g>${box(40,220,190,90,"#eef3f8","Investigar","información y acceso")}${box(285,220,190,90,"#fff0f1","Corregir","órdenes y sanciones")}${box(530,220,190,90,"#f7f1e7","Autorizar","supuestos previstos")}${box(155,356,190,76,"#17385f","Asesorar","criterio técnico")}${box(415,356,190,76,"#eef3f8","Informar","actividad y cuentas")}`)),right:copy("Del RGPD a la práctica española","Las categorías del artículo 58 RGPD aterrizan en una institución concreta: la AEPD.","La Agencia investiga, corrige, autoriza, asesora, coopera e informa de su actividad. Esa capacidad convierte el modelo europeo en aplicación efectiva en España.",[["Investigación","obtener evidencia"],["Corrección","órdenes y sanciones"],["Prevención","autorización y asesoramiento"]]),notes:"Aterrizar en la AEPD las categorías ya explicadas en el artículo 58 RGPD: independencia, condiciones de los miembros, establecimiento de la autoridad, competencia, funciones, poderes e informe de actividad. Mostrar que los poderes europeos tienen traducción institucional concreta en España."});

    const s45 = `<section class="slide-page" data-title="LOPDGDD · autoridades de control" data-background-color="#fffdf9"><div class="slide-inner">${top("LOPDGDD · Título VII")}
      <main class="aepd45-layout"><div class="copy-column"><p class="kicker">Sistema español de autoridades</p><h2>La LOPDGDD ordena la AEPD y reconoce la existencia de autoridades autonómicas en sus ámbitos competenciales.</h2><p class="body-copy">El modelo español combina una autoridad estatal con autoridades autonómicas, cada una con competencias delimitadas y necesidad de coordinación.</p></div>
      <div class="authority-control-map reveal-block stagger"><article><span>Autoridad estatal</span><strong>AEPD</strong><p>Autoridad administrativa independiente estatal, con competencias generales y representación española en el CEPD.</p><div class="authority-control-list"><b>Presidencia y Adjuntía</b><b>Consejo Consultivo</b><b>Inspección, promoción, autorizaciones y soporte</b></div></article><article><span>Autoridades autonómicas</span><strong>Ámbito propio</strong><p>Ejercen funciones en sectores públicos e instituciones autonómicas cuando su normativa lo prevé.</p><div class="authority-control-list"><b>País Vasco</b><b>Cataluña</b><b>Andalucía</b></div></article></div></main></div><aside class="notes">Explicar que la LOPDGDD regula las autoridades de protección de datos en España, con la AEPD como autoridad estatal y la existencia de autoridades autonómicas con competencias en sus respectivos ámbitos. Insistir en que esto introduce coordinación interna además de la cooperación europea.</aside></section>`;

    const s46 = section({title:"Naturaleza y régimen de la AEPD",bg:"#faf7f1",eyebrow:"Autoridad administrativa independiente",layout:"aepd46-layout",left:copy("Personalidad propia y capacidad plena","La AEPD tiene personalidad jurídica propia y plena capacidad pública y privada.","Actúa con independencia de los poderes públicos, se relaciona institucionalmente con el Gobierno, representa a España en el CEPD y dispone de presupuesto, personal y medios propios.",[["Naturaleza","autoridad administrativa independiente"],["Régimen","público y privado"],["Europa","representación en el CEPD"]]),right:panel(svg("Naturaleza y régimen de la AEPD",line("AEPD · NATURALEZA Y RÉGIMEN")+`${box(78,112,180,98,"#eef3f8","Personalidad","jurídica propia")}${box(290,112,180,98,"#f7f1e7","Capacidad","pública y privada")}${box(502,112,180,98,"#fff0f1","Independencia","poderes públicos")}${box(78,280,180,98,"#17385f","CEPD","representación")}${box(290,280,180,98,"#eef3f8","Presupuesto","propio")}${box(502,280,180,98,"#f7f1e7","Personal","funcionario/laboral")}<g stroke="#c74756" stroke-width="2.5" fill="none" opacity=".5"><path d="M258 161h28"/><path d="M470 161h28"/><path d="M258 329h28"/><path d="M470 329h28"/></g>`)),notes:"Explicar que la AEPD es una autoridad administrativa independiente con personalidad jurídica propia y plena capacidad pública y privada, que actúa con independencia de los poderes públicos. Señalar su relación institucional con el Gobierno, su representación en el CEPD, su presupuesto y el régimen de su personal."});

    const s47 = section({title:"Presidencia y Adjuntía",bg:"#fffdf9",eyebrow:"Dirección de la AEPD · actualización 2026",layout:"aepd47-layout",left:panel(svg("Presidencia y Adjuntía de la AEPD",line("AEPD · PRESIDENCIA Y ADJUNTÍA")+`<g transform="translate(180 118)"><rect width="400" height="108" rx="28" fill="#17385f"/><text x="200" y="38" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">PRESIDENTE</text><text x="200" y="78" text-anchor="middle" font-size="30" font-weight="900" fill="#fff" data-fit-width="330">Lorenzo Cotino Hueso</text></g><g transform="translate(210 286)"><rect width="340" height="96" rx="24" fill="#fff0f1"/><text x="170" y="35" text-anchor="middle" font-size="14" font-weight="850" fill="#c74756">ADJUNTO</text><text x="170" y="68" text-anchor="middle" font-size="25" font-weight="900" fill="#17385f" data-fit-width="286">Francisco Pérez Bes</text></g><g stroke="#c74756" stroke-width="3" fill="none" opacity=".65"><path d="M380 226v54"/></g>`)),right:copy("Órganos unipersonales de dirección","Presidencia y Adjuntía articulan la dirección institucional de la Agencia.","Su régimen conecta nombramiento, mandato, causas de cese, incompatibilidades y garantías de independencia. La versión actualiza los titulares vigentes.",[["Nombramiento","Gobierno a propuesta del Ministerio"],["Mandato","5 años"],["Control","cese tasado y tutela judicial"]]),notes:"El contenido jurídico básico sigue vigente: Presidencia y Adjuntía, nombramiento, mandato, cese e independencia. Actualización 2026: presidente Lorenzo Cotino Hueso y adjunto Francisco Pérez Bes."});

    const s48 = section({title:"Consejo Consultivo",bg:"#faf7f1",eyebrow:"Participación plural · no vinculante",layout:"aepd48-layout",left:copy("Una mirada plural sobre la actividad de la Agencia","El Consejo Consultivo aporta perspectivas institucionales, profesionales, académicas, empresariales y sociales.","Su carácter no vinculante no le resta utilidad: permite incorporar sensibilidad práctica y pluralidad de actores al funcionamiento de la AEPD.",[["Naturaleza","órgano consultivo no vinculante"],["Valor","pluralidad institucional y social"],["Función","aportar criterio y perspectiva"]],"aepd-chip-grid-41 two"),right:panel(svg("Composición plural del Consejo Consultivo de la AEPD",line("CONSEJO CONSULTIVO · COMPOSICIÓN PLURAL")+`${box(72,120,160,82,"#eef3f8","Instituciones","Congreso, Senado")}${box(300,120,160,82,"#f7f1e7","Comunidades","y entidades")}${box(528,120,160,82,"#fff0f1","Profesionales","y empresas")}${box(72,278,160,82,"#fff0f1","Universidad","expertos")}${box(300,278,160,82,"#17385f","AEPD","escucha plural")}${box(528,278,160,82,"#eef3f8","Sindicatos","sociedad")}<g stroke="#c74756" stroke-width="2.5" fill="none" opacity=".55"><path d="M232 161h64"/><path d="M460 161h64"/><path d="M232 319h64"/><path d="M460 319h64"/><path d="M380 205v67"/></g>`)),notes:"Explicar que la AEPD dispone de un Consejo Consultivo de composición plural y carácter no vinculante, en el que están representadas instituciones públicas, autoridades autonómicas, organizaciones empresariales, profesionales, universidades, sindicatos y otros actores. Su función es aportar perspectivas diversas a la actividad de la Agencia."});

    const s49 = section({title:"Autoridades autonómicas de protección de datos",bg:"#fffdf9",eyebrow:"Coordinación interna · sistema español",layout:"aepd49-layout",left:copy("La AEPD no está sola","España cuenta también con autoridades autonómicas de protección de datos con competencias en sus ámbitos propios.","Esto permite explicar que la cooperación no solo es europea: también existe coordinación interna dentro del sistema español.",[["País Vasco","autoridad vasca"],["Cataluña","APDCAT"],["Andalucía","Consejo de Transparencia y PD"]]),right:panel(svg("Autoridades autonómicas de protección de datos en España",line("AUTORIDADES AUTONÓMICAS")+`<g transform="translate(180 104)"><rect width="400" height="96" rx="30" fill="#17385f"/><text x="200" y="35" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">SISTEMA ESPAÑOL</text><text x="200" y="66" text-anchor="middle" font-size="28" font-weight="900" fill="#fff">Autoridades de control</text><text x="200" y="85" text-anchor="middle" font-size="12.5" fill="#dbe6f2">competencias propias y coordinación interna</text></g><g stroke="#c74756" stroke-width="2.8" fill="none" stroke-linecap="round" stroke-linejoin="round" opacity=".68"><path d="M380 200v44"/><path d="M150 244H610"/><path d="M150 244v64"/><path d="M380 244v64"/><path d="M610 244v64"/></g>${box(60,308,180,84,"#eef3f8","País Vasco","autoridad propia")}${box(290,308,180,84,"#fff0f1","Cataluña","APDCAT")}${box(520,308,180,84,"#f7f1e7","Andalucía","CTPDA")}<rect x="194" y="408" width="372" height="28" rx="14" fill="#fff" stroke="#e4ddd2"/><text x="380" y="427" text-anchor="middle" font-size="12.4" font-weight="850" fill="#17385f" data-fit-width="330">Coordinación interna además de cooperación europea</text>`)),notes:"Explicar que la AEPD no es la única autoridad de protección de datos en España. Existen autoridades autonómicas con competencias en sus respectivos ámbitos, como las de País Vasco, Cataluña y Andalucía. Esto permite introducir la necesidad de coordinación interna además de la cooperación europea."});

    const s50 = `<section class="slide-page" data-title="El Comité Europeo de Protección de Datos" data-background-color="#faf7f1"><div class="slide-inner">${top("IV · cooperación europea")}
      <main class="edpb50-transition"><div class="copy-column"><p class="kicker">Del sistema español al europeo</p><h2>El Comité Europeo de Protección de Datos</h2><p class="body-copy">Tras la AEPD, el curso cambia de escala: de la autoridad estatal y la coordinación interna al órgano europeo que garantiza cooperación y coherencia.</p></div><div class="edpb50-card reveal-block"><span>Bloque IV</span><strong>Cooperación, coherencia y criterios comunes</strong><p>El CEPD conecta a las autoridades nacionales, al SEPD y a la arquitectura europea de protección de datos.</p><div class="mini"><b>Miembros</b><b>Funciones</b><b>Decisiones</b></div></div></main></div><aside class="notes">Usar esta diapositiva como transición visual hacia el Comité Europeo de Protección de Datos. El objetivo no es desarrollar todavía sus funciones, sino marcar el cambio de escala: de la AEPD y las autoridades españolas al sistema europeo de cooperación y coherencia.</aside></section>`;

    root.insertAdjacentHTML("beforeend", [s41,s42,s43,s44,s45,s46,s47,s48,s49,s50].join(""));
    if (window.fitSvgDiagramText) window.fitSvgDiagramText(root);
    if (window.Reveal) { if (typeof Reveal.sync === "function") Reveal.sync(); if (typeof Reveal.layout === "function") Reveal.layout(); }
  }

  if(document.readyState === "loading") document.addEventListener("DOMContentLoaded", injectSlides41To50, {once:true});
  else injectSlides41To50();
})();
