(() => {
  "use strict";
  const EXTRA_ID = "slides-61-70-injected";

  const logo = '<img class="aepd-logo" src="assets/aepd-logo.svg" alt="AEPD – Agencia Española de Protección de Datos" />';
  const topbar = (eyebrow) => `<header class="topbar"><div class="brand">${logo}</div><p>${eyebrow}</p></header>`;
  const chips = (items, cls = "info-chip-grid-61") => `<div class="${cls}">${items.map(([a,b]) => `<article><span>${a}</span><strong>${b}</strong></article>`).join("")}</div>`;
  const section = ({title,bg,eyebrow,layout,copy,visual,notes,reverse=false}) => `
    <section class="slide-page" data-title="${title}" data-background-color="${bg}">
      <div class="slide-inner">${topbar(eyebrow)}<main class="${layout}">${reverse ? visual + copy : copy + visual}</main></div>
      <aside class="notes">${notes}</aside>
    </section>`;
  const copy = (kicker,h2,body,chipItems,cls="info-chip-grid-61") => `<div class="copy-column"><p class="kicker">${kicker}</p><h2>${h2}</h2><p class="body-copy">${body}</p>${chips(chipItems,cls)}</div>`;
  const panel = (svg, tall=false) => `<figure class="diagram-panel-61-70${tall ? " tall" : ""}">${svg}</figure>`;
  const box = (x,y,w,h,fill,t1,t2="",t3="") => `<g transform="translate(${x} ${y})"><rect width="${w}" height="${h}" rx="22" fill="${fill}"/><text x="${w/2}" y="${Math.round(h*.38)}" text-anchor="middle" font-size="16" font-weight="850" fill="#17385f" data-fit-width="${w-28}">${t1}</text>${t2 ? `<text x="${w/2}" y="${Math.round(h*.62)}" text-anchor="middle" font-size="12.5" fill="#66778a" data-fit-width="${w-28}">${t2}</text>` : ""}${t3 ? `<text x="${w/2}" y="${Math.round(h*.80)}" text-anchor="middle" font-size="12.5" fill="#66778a" data-fit-width="${w-28}">${t3}</text>` : ""}</g>`;
  const svgWrap = (label, inner, view="0 0 760 470") => `<svg class="safe-diagram" viewBox="${view}" role="img" aria-label="${label}"><rect width="760" height="470" rx="34" fill="#fff"/><rect x="28" y="28" width="704" height="414" rx="28" fill="#fbf8f2" stroke="#e8dfd1"/><g font-family="Inter,Arial">${inner}</g></svg>`;
  const titleLine = (t) => `<text x="56" y="70" font-size="15" font-weight="850" fill="#c74756" data-fit-width="620">${t}</text>`;

  function injectSlides61To70(){
    const root = document.querySelector(".reveal .slides");
    if(!root || document.getElementById(EXTRA_ID)) return;
    const style = document.createElement("style");
    style.id = EXTRA_ID;
    style.textContent = `
      .edpb61-layout,.edpb62-layout,.edpb63-layout,.edpb64-layout,.edpb65-layout,.edpb66-layout,.edpb67-layout,.edpb68-layout,.imi69-layout,.imi70-layout{display:grid;gap:52px;align-items:center;flex:1;min-height:0;}
      .edpb61-layout,.edpb63-layout,.edpb65-layout,.edpb67-layout,.imi69-layout{grid-template-columns:minmax(0,1fr) 640px;}
      .edpb62-layout,.edpb64-layout,.edpb66-layout,.edpb68-layout,.imi70-layout{grid-template-columns:640px minmax(0,1fr);}
      .diagram-panel-61-70{margin:0;height:430px;overflow:hidden;border:0;border-radius:30px;background:transparent;box-shadow:none;}
      .diagram-panel-61-70.tall{height:470px;}
      .diagram-panel-61-70 svg{display:block;width:100%;height:100%;overflow:hidden;}
      .edpb61-layout h2,.edpb62-layout h2,.edpb63-layout h2,.edpb64-layout h2,.edpb65-layout h2,.edpb66-layout h2,.edpb67-layout h2,.edpb68-layout h2,.imi69-layout h2,.imi70-layout h2{font-size:49px;line-height:1.01;}
      .edpb61-layout .body-copy,.edpb62-layout .body-copy,.edpb63-layout .body-copy,.edpb64-layout .body-copy,.edpb65-layout .body-copy,.edpb66-layout .body-copy,.edpb67-layout .body-copy,.edpb68-layout .body-copy,.imi69-layout .body-copy,.imi70-layout .body-copy{font-size:20px!important;line-height:1.24!important;}
      .info-chip-grid-61{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:24px;}.info-chip-grid-61.two{grid-template-columns:repeat(2,minmax(0,1fr));}
      .info-chip-grid-61 article{min-height:78px;padding:13px 14px;overflow:hidden;border-top:2px solid rgba(199,71,86,.34);border-radius:0 0 20px 20px;background:rgba(255,255,255,.56);}
      .info-chip-grid-61 span{color:var(--gold);font-size:10px;font-weight:850;letter-spacing:.10em;text-transform:uppercase;}.info-chip-grid-61 strong{display:block;margin-top:7px;color:var(--blue-deep);font-size:17px;line-height:1.08;overflow-wrap:anywhere;}
      .bands-61{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:24px;}.bands-61 article{min-height:150px;padding:18px;border-radius:24px;border:1px solid rgba(31,61,99,.10);background:rgba(255,255,255,.72);box-shadow:0 16px 44px rgba(31,61,99,.07);overflow:hidden;}.bands-61 span{display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:var(--blue-deep);color:#fff;font-size:13px;font-weight:900;}.bands-61 article:nth-child(2) span{background:var(--gold);}.bands-61 article:nth-child(3) span,.bands-61 article:nth-child(4) span{background:var(--red);}.bands-61 strong{display:block;margin-top:12px;color:var(--blue-deep);font-size:20px;line-height:1.04;}.bands-61 p{margin:9px 0 0!important;color:var(--muted);font-size:13.5px!important;line-height:1.18!important;}
    `;
    document.head.appendChild(style);

    const s61 = section({title:"Dictámenes del CEPD",bg:"#fffdf9",eyebrow:"CEPD · dictámenes",layout:"edpb61-layout",copy:copy("Opiniones y posición común","Los dictámenes del CEPD ayudan a anticipar una aplicación homogénea antes de que cada autoridad decida.","Funcionan como punto de convergencia: ordenan cuestiones generales, proyectos nacionales y procedimientos previstos por el RGPD.",[["Objeto","criterio previo y armonizador"],["Uso","autoridades, responsables y encargados"],["Resultado","menos fragmentación interpretativa"]]),visual:panel(svgWrap("Dictámenes del Comité Europeo de Protección de Datos",titleLine("DICTÁMENES DEL CEPD · CONVERGENCIA ANTES DE DECIDIR")+`${box(60,118,190,72,"#eef3f8","Cuestión general","interpretación")}${box(510,118,190,72,"#f7f1e7","Proyecto nacional","consulta prevista")}<g stroke="#c74756" stroke-width="2.8" fill="none" stroke-linecap="round" stroke-linejoin="round" opacity=".66"><path d="M250 154H286Q304 154 318 168L336 186"/><path d="M510 154H474Q456 154 442 168L424 186"/></g><g transform="translate(250 186)"><rect width="260" height="82" rx="26" fill="#17385f"/><text x="130" y="32" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">DICTAMEN CEPD</text><text x="130" y="59" text-anchor="middle" font-size="14" fill="#fff">criterio común antes de la decisión</text></g><g stroke="#c74756" stroke-width="2.6" fill="none" stroke-linecap="round" opacity=".62"><path d="M380 268v36"/><path d="M150 304H610"/><path d="M150 304v22"/><path d="M380 304v22"/><path d="M610 304v22"/></g>${box(60,326,180,78,"#eef3f8","Procedimiento","casos previstos")}${box(290,326,180,78,"#fff0f1","Armonización","criterio común")}${box(520,326,180,78,"#f7f1e7","Publicación","transparencia")}`)),notes:"Explicar que el Comité emite dictámenes en procedimientos previstos por el RGPD y en asuntos de aplicación general. Los dictámenes permiten anticipar y armonizar posiciones antes de que las autoridades nacionales adopten determinadas decisiones."});

    const s62 = section({title:"Directrices, recomendaciones y buenas prácticas",bg:"#faf7f1",eyebrow:"CEPD · interpretación práctica",layout:"edpb62-layout",reverse:true,visual:panel(svgWrap("Directrices, recomendaciones y buenas prácticas del CEPD",titleLine("DIRECTRICES · RECOMENDACIONES · BUENAS PRÁCTICAS")+`${box(70,120,180,206,"#eef3f8","Conceptos","interpretación","jurídica")}<g transform="translate(290 98)"><rect width="180" height="250" rx="26" fill="#17385f"/><text x="90" y="72" text-anchor="middle" font-size="20" font-weight="900" fill="#fff">Criterio</text><text x="90" y="106" text-anchor="middle" font-size="13" fill="#dbe6f2">coherente</text><text x="90" y="132" text-anchor="middle" font-size="13" fill="#dbe6f2">para todos</text><circle cx="90" cy="188" r="34" fill="#f1b434"/><text x="90" y="198" text-anchor="middle" font-size="32" font-weight="900" fill="#17385f">✓</text></g>${box(510,120,180,206,"#fff0f1","Práctica","cumplimiento","supervisión")}<rect x="110" y="382" width="540" height="38" rx="17" fill="#fff" stroke="#e4ddd2"/><text x="380" y="407" text-anchor="middle" font-size="14" font-weight="850" fill="#17385f" data-fit-width="500">Orientan la aplicación diaria del RGPD.</text>`)),copy:copy("La capa interpretativa","Las directrices del CEPD convierten conceptos abiertos del RGPD en criterios aplicables.","No sustituyen al Reglamento, pero influyen decisivamente en la supervisión, el cumplimiento y la interpretación común.",[["Norma","el RGPD sigue siendo la fuente"],["Criterio","guía práctica para aplicar la norma"],["Efecto","homogeneidad en el EEE"]]),notes:"Explicar que las directrices del CEPD son una herramienta clave para interpretar conceptos del RGPD y promover una aplicación homogénea. Aunque no sustituyen al Reglamento, influyen en la práctica supervisora y en el cumplimiento."});

    const s63 = section({title:"Consultas públicas del CEPD",bg:"#fffdf9",eyebrow:"Participación · antes de adoptar criterios",layout:"edpb63-layout",copy:copy("El criterio también se abre a observaciones","Las consultas públicas permiten que mercado, sociedad civil y expertos contribuyan antes de cerrar una directriz.","El proceso muestra que la interpretación europea se contrasta con quienes tendrán que aplicarla.",[["Entrada","proyecto de directriz"],["Participación","observaciones y respuestas"],["Salida","versión definitiva más robusta"]]),visual:panel(svgWrap("Proceso de consulta pública del CEPD",titleLine("CONSULTA PÚBLICA · DEL BORRADOR AL CRITERIO FINAL")+`<g stroke="#d7dee8" stroke-width="4" fill="none" stroke-linecap="round"><path d="M118 154H642"/></g><g transform="translate(100 136)"><circle cx="18" cy="18" r="18" fill="#17385f"/><text x="18" y="24" text-anchor="middle" font-size="13" font-weight="900" fill="#fff">1</text></g><g transform="translate(274 136)"><circle cx="18" cy="18" r="18" fill="#f1b434"/><text x="18" y="24" text-anchor="middle" font-size="13" font-weight="900" fill="#17385f">2</text></g><g transform="translate(448 136)"><circle cx="18" cy="18" r="18" fill="#c74756"/><text x="18" y="24" text-anchor="middle" font-size="13" font-weight="900" fill="#fff">3</text></g><g transform="translate(622 136)"><circle cx="18" cy="18" r="18" fill="#17385f"/><text x="18" y="24" text-anchor="middle" font-size="13" font-weight="900" fill="#fff">4</text></g>${box(48,190,145,108,"#eef3f8","Borrador","texto inicial")}${box(222,190,145,108,"#f7f1e7","Consulta","aportaciones")}${box(396,190,145,108,"#fff0f1","Análisis","del CEPD")}<g transform="translate(570 190)"><rect width="145" height="108" rx="22" fill="#17385f"/><text x="72.5" y="43" text-anchor="middle" font-size="16" font-weight="850" fill="#fff">Adopción</text><text x="72.5" y="70" text-anchor="middle" font-size="12.5" fill="#dbe6f2">versión final</text></g><g transform="translate(110 342)"><rect width="540" height="54" rx="20" fill="#fff" stroke="#e4ddd2"/><text x="270" y="22" text-anchor="middle" font-size="11.5" font-weight="850" fill="#c74756">PARTICIPACIÓN</text><text x="270" y="41" text-anchor="middle" font-size="13.5" font-weight="850" fill="#17385f" data-fit-width="495">mercado · sociedad civil · expertos → criterio más robusto</text></g>`)),notes:"Explicar que el CEPD somete muchos proyectos de directrices a consulta pública. Permite formular observaciones antes de la adopción definitiva de determinados documentos."});

    const s64 = section({title:"Registro de códigos de conducta",bg:"#faf7f1",eyebrow:"Autorregulación supervisada",layout:"edpb64-layout",reverse:true,visual:panel(svgWrap("Registro europeo de códigos de conducta",titleLine("CÓDIGOS DE CONDUCTA · PROCESO SUPERVISADO")+`<g transform="translate(250 104)"><rect width="260" height="66" rx="23" fill="#17385f"/><text x="130" y="28" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">CÓDIGO DE CONDUCTA</text><text x="130" y="50" text-anchor="middle" font-size="12.5" fill="#dbe6f2">adaptar el RGPD a un sector concreto</text></g><g stroke="#c74756" stroke-width="3" fill="none" stroke-linecap="round" stroke-linejoin="round" opacity=".7"><path d="M240 282h46"/><path d="M474 282h42"/></g><path d="M276 274l10 8-10 8M506 274l10 8-10 8" fill="none" stroke="#c74756" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><g transform="translate(60 212)"><circle cx="24" cy="24" r="24" fill="#17385f"/><text x="24" y="30" text-anchor="middle" font-size="14" font-weight="900" fill="#fff">1</text></g><g transform="translate(290 212)"><circle cx="24" cy="24" r="24" fill="#c74756"/><text x="24" y="30" text-anchor="middle" font-size="14" font-weight="900" fill="#fff">2</text></g><g transform="translate(520 212)"><circle cx="24" cy="24" r="24" fill="#f1b434"/><text x="24" y="30" text-anchor="middle" font-size="14" font-weight="900" fill="#17385f">3</text></g>${box(60,258,180,102,"#eef3f8","Sector","redacta reglas","y prácticas")}${box(290,258,180,102,"#fff0f1","Autoridad","aprueba","y supervisa")}${box(520,258,180,102,"#f7f1e7","Dimensión UE","registro","y visibilidad")}<rect x="118" y="392" width="524" height="36" rx="17" fill="#fff" stroke="#e4ddd2"/><text x="380" y="416" text-anchor="middle" font-size="12.8" font-weight="850" fill="#17385f" data-fit-width="480">Autorregulación, pero con validación y seguimiento institucional.</text>`)),copy:copy("Más que sanciones","El registro de códigos recuerda que el RGPD también impulsa mecanismos de cumplimiento supervisado.","Los códigos permiten adaptar principios generales a sectores concretos, con aprobación y seguimiento institucional.",[["Sector","traduce el RGPD a prácticas"],["Autoridad","valida y supervisa"],["CEPD","coordina la dimensión europea"]]),notes:"Explicar que el CEPD mantiene información pública sobre instrumentos europeos como códigos de conducta. Sirve para visualizar que el cumplimiento incluye mecanismos de autorregulación supervisada."});

    const s65 = section({title:"Sistemas internos del CEPD · Confluence",bg:"#fffdf9",eyebrow:"Trabajo interno · coordinación diaria",layout:"edpb65-layout",copy:copy("Detrás de los documentos públicos","El trabajo del CEPD necesita una infraestructura interna para coordinar reuniones, documentos y calendarios.","Cuando no hay captura pública verificable de la interfaz actual, es mejor explicar la función de la herramienta y no inventar su aspecto.",[["Reuniones","agenda, actas y seguimiento"],["Documentos","borradores y versiones"],["Recursos","espacios compartidos de trabajo"]]),visual:panel(svgWrap("Función interna de Confluence en el trabajo del CEPD",titleLine("CONFLUENCE · ESPACIO DE TRABAJO INTERNO")+`<g transform="translate(250 102)"><rect width="260" height="76" rx="24" fill="#17385f"/><text x="130" y="31" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">ESPACIO COMÚN</text><text x="130" y="57" text-anchor="middle" font-size="14" fill="#fff">cooperación diaria</text></g><g stroke="#c74756" stroke-width="2.6" fill="none" stroke-linecap="round" opacity=".58"><path d="M380 178v54"/><path d="M150 232H610"/><path d="M150 232v30"/><path d="M380 232v30"/><path d="M610 232v30"/></g>${box(60,262,180,102,"#eef3f8","Reuniones","agenda y actas","seguimiento")}${box(290,262,180,102,"#fff0f1","Documentos","borradores","y versiones")}${box(520,262,180,102,"#f7f1e7","Recursos","materiales","compartidos")}<g transform="translate(112 392)"><rect width="536" height="34" rx="17" fill="#fff" stroke="#e4ddd2"/><text x="268" y="23" text-anchor="middle" font-size="12.8" font-weight="850" fill="#17385f" data-fit-width="490">Infraestructura funcional, no reconstrucción de una interfaz.</text></g>`)),notes:"Mostrar que la cooperación requiere herramientas internas para organizar reuniones, calendarios, subgrupos, documentos y recursos. No inventar una interfaz actual si no hay fuente pública verificable."});

    const s66 = section({title:"Confluence · grupos de expertos",bg:"#faf7f1",eyebrow:"Trabajo especializado",layout:"edpb66-layout",reverse:true,visual:panel(svgWrap("Grupos de expertos del CEPD",titleLine("GRUPOS DE EXPERTOS · ESPECIALIZACIÓN TEMÁTICA")+`<g transform="translate(250 98)"><rect width="260" height="70" rx="24" fill="#17385f"/><text x="130" y="29" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">TRABAJO TÉCNICO</text><text x="130" y="53" text-anchor="middle" font-size="14" fill="#fff">grupos especializados</text></g>${box(55,205,190,74,"#eef3f8","Tecnología","IA · cookies")}${box(285,205,190,74,"#fff0f1","Transferencias","terceros países")}${box(515,205,190,74,"#f7f1e7","Cooperación","casos transfronterizos")}${box(55,304,190,74,"#f7f1e7","Enforcement","aplicación")}${box(285,304,190,74,"#eef3f8","Redes sociales","plataformas")}${box(515,304,190,74,"#fff0f1","Finanzas","pagos y banca")}<g transform="translate(128 402)"><rect width="504" height="28" rx="14" fill="#fff" stroke="#e4ddd2"/><text x="252" y="19" text-anchor="middle" font-size="12.2" font-weight="850" fill="#17385f" data-fit-width="464">análisis y borradores → propuestas para el Comité</text></g>`)),copy:`<div class="copy-column"><p class="kicker">La especialización permite avanzar</p><h2>Los grupos de expertos preparan el trabajo técnico que después puede convertirse en directrices, dictámenes o decisiones.</h2><p class="body-copy">Confluence permite coordinar aportaciones de múltiples autoridades sobre materias especializadas.</p><div class="bands-61"><article><span>1</span><strong>Especializar</strong><p>Repartir materias complejas.</p></article><article><span>2</span><strong>Redactar</strong><p>Crear borradores y análisis.</p></article><article><span>3</span><strong>Contrastar</strong><p>Aportaciones nacionales.</p></article><article><span>4</span><strong>Elevar</strong><p>Propuestas al Comité.</p></article></div></div>`,notes:"Explicar que los grupos de expertos trabajan de manera especializada en tecnología, transferencias internacionales, aplicación, redes sociales, cooperación o cuestiones financieras."});

    const s67 = section({title:"Comité de Supervisión Coordinada",bg:"#fffdf9",eyebrow:"Supervisión coordinada · grandes sistemas europeos",layout:"edpb67-layout",copy:copy("Cuando un sistema supera a un Estado","Algunos sistemas europeos requieren supervisión coordinada entre el SEPD y las autoridades nacionales.","El Comité de Supervisión Coordinada refleja otra capa del modelo: sistemas y organismos europeos que procesan datos a escala transnacional.",[["Quiénes","SEPD + autoridades nacionales"],["Por qué","sistemas europeos compartidos"],["Para qué","supervisión coherente y estable"]]),visual:panel(svgWrap("Ámbito del Comité de Supervisión Coordinada",titleLine("COORDINATED SUPERVISION COMMITTEE")+`<g transform="translate(275 118)"><circle cx="105" cy="105" r="94" fill="#17385f"/><text x="105" y="92" text-anchor="middle" font-size="18" font-weight="850" fill="#f1b434">CSC</text><text x="105" y="122" text-anchor="middle" font-size="16" font-weight="850" fill="#fff" data-fit-width="150">supervisión coordinada</text></g>${box(56,118,160,64,"#eef3f8","SIS")}${box(544,118,160,64,"#eef3f8","Europol")}${box(56,215,160,64,"#f7f1e7","VIS")}${box(544,215,160,64,"#f7f1e7","EES")}${box(56,312,160,64,"#fff0f1","Eurojust")}${box(544,312,160,64,"#fff0f1","Eurodac")}<rect x="196" y="414" width="368" height="42" rx="16" fill="#fff" stroke="#e4ddd2"/><text x="380" y="441" text-anchor="middle" font-size="13.5" font-weight="850" fill="#17385f" data-fit-width="330">También: CIS, EPPO, IMI y Prüm II.</text>`),true),notes:"Explicar que determinados grandes sistemas y organismos europeos requieren supervisión coordinada entre el SEPD y las autoridades nacionales. En 2026 incluye, entre otros, SIS, Europol, VIS, CIS, EES, EPPO, Eurojust, IMI, Prüm II y Eurodac."});

    const s68 = section({title:"Comité de Supervisión Coordinada · Confluence",bg:"#faf7f1",eyebrow:"CSC · infraestructura interna",layout:"edpb68-layout",reverse:true,visual:panel(svgWrap("Infraestructura interna del Comité de Supervisión Coordinada",titleLine("CSC · COORDINACIÓN INTERNA")+`<g transform="translate(250 98)"><rect width="260" height="78" rx="25" fill="#17385f"/><text x="130" y="31" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">CSC</text><text x="130" y="57" text-anchor="middle" font-size="14" fill="#fff">espacio común de trabajo</text></g><g stroke="#c74756" stroke-width="2.6" fill="none" stroke-linecap="round" opacity=".6"><path d="M380 176v50"/><path d="M150 226H610"/><path d="M150 226v30"/><path d="M380 226v30"/><path d="M610 226v30"/></g>${box(60,256,180,96,"#eef3f8","Reuniones","agenda","y acuerdos")}${box(290,256,180,96,"#f7f1e7","Recursos","documentos","compartidos")}${box(520,256,180,96,"#fff0f1","Seguimiento","acciones","y tareas")}<g transform="translate(88 386)"><rect width="584" height="42" rx="18" fill="#fff" stroke="#e4ddd2"/><text x="292" y="18" text-anchor="middle" font-size="11.5" font-weight="850" fill="#c74756">PROCESO ESTABLE</text><text x="292" y="34" text-anchor="middle" font-size="12.5" font-weight="850" fill="#17385f" data-fit-width="540">preparar · coordinar · ejecutar · revisar</text></g>`)),copy:copy("Misma lógica: coordinación estable","La supervisión coordinada también necesita un espacio común para recursos, reuniones y seguimiento.","Si no hay una interfaz pública verificable, conviene explicar su papel operativo sin reconstruir una pantalla ficticia.",[["Coordinación","organizar reuniones y documentos"],["Trazabilidad","seguir decisiones y tareas"],["Continuidad","mantener memoria institucional"]]),notes:"Mostrar la infraestructura interna que facilita reuniones, recursos y coordinación del comité de supervisión. La utilidad didáctica es enseñar que la supervisión coordinada necesita procedimientos y herramientas estables."});

    const s69 = section({title:"IMI · visión general",bg:"#fffdf9",eyebrow:"Internal Market Information System",layout:"imi69-layout",copy:copy("La cooperación convertida en flujo de trabajo","IMI es la herramienta práctica que convierte obligaciones de cooperación en expedientes trazables.","Permite registrar comunicaciones, solicitudes y notificaciones relacionadas con procedimientos transfronterizos del RGPD.",[["Qué es","infraestructura de cooperación administrativa"],["Para qué","solicitudes y notificaciones"],["Valor","trazabilidad de fases y plazos"]],"imi-chip-grid"),visual:panel(svgWrap("Funcionamiento general de IMI en cooperación RGPD",titleLine("IMI · INFRAESTRUCTURA OPERATIVA")+`${box(70,128,180,118,"#eef3f8","Autoridad A","solicitud")}<g transform="translate(290 108)"><rect width="180" height="158" rx="26" fill="#17385f"/><text x="90" y="58" text-anchor="middle" font-size="40" font-weight="900" fill="#fff">IMI</text><text x="90" y="94" text-anchor="middle" font-size="13" fill="#dbe6f2">registro y trazas</text></g>${box(510,128,180,118,"#fff0f1","Autoridad B","respuesta")}<g stroke="#c74756" stroke-width="3" fill="none" stroke-linecap="round"><path d="M254 187h32"/><path d="M474 187h32"/></g><rect x="110" y="328" width="540" height="60" rx="20" fill="#fff" stroke="#e4ddd2"/><text x="380" y="365" text-anchor="middle" font-size="15" font-weight="850" fill="#17385f" data-fit-width="500">Cooperación jurídica, pero con workflow administrativo.</text>`)),notes:"Explicar que IMI es una herramienta práctica de cooperación entre autoridades. Permite registrar comunicaciones, solicitudes y notificaciones relacionadas con procedimientos transfronterizos del RGPD."});

    const s70 = section({title:"IMI · solicitudes",bg:"#faf7f1",eyebrow:"Solicitudes y comunicaciones RGPD",layout:"imi70-layout",reverse:true,visual:panel(svgWrap("Tipos de solicitudes y comunicaciones RGPD en IMI",titleLine("IMI · SOLICITUDES RGPD")+`<g transform="translate(275 98)"><rect width="210" height="72" rx="24" fill="#17385f"/><text x="105" y="30" text-anchor="middle" font-size="14" font-weight="850" fill="#f1b434">IMI</text><text x="105" y="55" text-anchor="middle" font-size="15" fill="#fff">solicitud RGPD</text></g><g stroke="#c74756" stroke-width="2.7" fill="none" stroke-linecap="round" opacity=".62"><path d="M380 170v46"/><path d="M150 216H610"/><path d="M150 216v28"/><path d="M380 216v28"/><path d="M610 216v28"/></g>${box(55,244,190,92,"#eef3f8","Asistencia mutua","art. 61 RGPD")}${box(285,244,190,92,"#fff0f1","Autoridad principal","arts. 56 y 60")}${box(515,244,190,92,"#f7f1e7","Coherencia","art. 63 y ss.")}<g transform="translate(118 368)"><rect width="524" height="58" rx="20" fill="#fff" stroke="#e4ddd2"/><line x1="262" y1="10" x2="262" y2="48" stroke="#e4ddd2"/><text x="131" y="24" text-anchor="middle" font-size="11.5" font-weight="850" fill="#c74756">GESTIÓN</text><text x="131" y="43" text-anchor="middle" font-size="14" font-weight="850" fill="#17385f">plazos y respuestas</text><text x="393" y="24" text-anchor="middle" font-size="11.5" font-weight="850" fill="#c74756">TRAZABILIDAD</text><text x="393" y="43" text-anchor="middle" font-size="14" font-weight="850" fill="#17385f">estado e historial</text></g>`)),copy:copy("Del artículo al formulario","IMI estructura solicitudes y comunicaciones para que cada fase transfronteriza quede ordenada.","La pantalla ilustra cómo asistencia mutua, autoridad principal y coherencia se convierten en categorías operativas.",[["Solicitud","tipo y base jurídica"],["Gestión","plazos y respuestas"],["Trazabilidad","constancia formal del expediente"]],"imi-chip-grid"),notes:"Explicar que la herramienta permite canalizar distintos tipos de solicitudes y comunicaciones basadas en artículos concretos del RGPD, como asistencia mutua o actuaciones relacionadas con la autoridad principal."});

    root.insertAdjacentHTML("beforeend", [s61,s62,s63,s64,s65,s66,s67,s68,s69,s70].join(""));
  }

  if(document.readyState === "loading") document.addEventListener("DOMContentLoaded", injectSlides61To70, { once:true });
  else injectSlides61To70();
})();
